# Generated by Django 5.1.3 on 2024-11-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_album_artist_remove_song_artist_song_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_art_path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
